"""empty message

Revision ID: b0ead633648c
Revises: 
Create Date: 2020-12-11 18:51:40.831900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ead633648c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments')
    op.drop_table('employees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('salary', sa.FLOAT(), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=False),
    sa.Column('department_id', sa.INTEGER(), nullable=False)
    )
    op.create_table('departments',
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
